name:    mail2
doc:     Build mail2 project
default: [clean, test, build]

properties:
  NAME:      'mail2'
  VERSION:   '#{run("changelog", "release", "version")}'
  BUILD_DIR: 'build'
  ARC_DIR:   '#{BUILD_DIR}/#{NAME}-#{VERSION}'
  DEPENDENCIES:
  - "github.com/mitchellh/gox"
  - 'github.com/jordan-wright/email'

targets:

  deps:
    doc: Install Go dependencies
    steps:
    - for: dependency
      in:  DEPENDENCIES
      do:
      - print: 'Getting dependency #{dependency}...'
      - 'go get "#{dependency}"'

  test:
    doc: Run Go tests
    steps:
    - 'go test'

  build:
    doc: Build Go application
    steps:
    - mkdir: '#{BUILD_DIR}'
    - 'go build -o #{BUILD_DIR}/#{NAME}'

  archive:
    doc: Build distribution archive
    steps:
    - mkdir: '#{BUILD_DIR}/#{NAME}-#{VERSION}/bin/'
    - 'gox -output=#{ARC_DIR}/bin/{{.Dir}}_{{.OS}}_{{.Arch}}'
    - copy:
      - 'README.md'
      - 'CHANGELOG.yml'
      - 'LICENSE.txt'
      todir: '#{ARC_DIR}'
    - tar:    '**/*'
      dir:    '#{ARC_DIR}'
      prefix: '#{NAME}-#{VERSION}'
      to:     '#{BUILD_DIR}/#{NAME}-#{VERSION}.tar.gz'

  release:
    doc: Make a release
    depends: [clean, test, archive]
    steps:
    - 'release'

  clean:
    doc: Clean generated files
    steps:
    - delete: '#{BUILD_DIR}'

