# NeON build file (http://github.com/c4s4/neon)

extends: golang
default: [fmt, check, test]
expose:  [fmt, check, test, release]
configuration: '~/.neon/github.yml'
# GITHUB_TOKEN: 'abcdefghijklmnopqrstuvwxyz0123456789'

targets:

  test:
    doc: Run Go tests
    steps:
    - dotenv: '~/.env/gmail.env'
    - super:
